-- MySQL Script generated by MySQL Workbench
-- Tue Nov  3 19:08:49 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema je7986_univ_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema je7986_univ_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `je7986_univ_db` DEFAULT CHARACTER SET utf8 ;
USE `je7986_univ_db` ;

-- -----------------------------------------------------
-- Table `je7986_univ_db`.`DEPARTMENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `je7986_univ_db`.`DEPARTMENT` (
  `department_number` INT NOT NULL,
  `department_name` VARCHAR(45) NULL,
  PRIMARY KEY (`department_number`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `je7986_univ_db`.`STUDENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `je7986_univ_db`.`STUDENT` (
  `student_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NULL,
  `department_number_of_major` INT NULL,
  `year_admitted` DATETIME NULL,
  `birthday` DATETIME NULL,
  `DEPARTMENT_department_number` INT NOT NULL,
  PRIMARY KEY (`student_id`),
  UNIQUE INDEX `student_id_UNIQUE` (`student_id` ASC) VISIBLE,
  INDEX `fk_STUDENT_DEPARTMENT1_idx` (`DEPARTMENT_department_number` ASC) VISIBLE,
  CONSTRAINT `fk_STUDENT_DEPARTMENT1`
    FOREIGN KEY (`DEPARTMENT_department_number`)
    REFERENCES `je7986_univ_db`.`DEPARTMENT` (`department_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `je7986_univ_db`.`PROFESSOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `je7986_univ_db`.`PROFESSOR` (
  `professor_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `office_room_number` VARCHAR(45) NULL,
  `office_hour_start` VARCHAR(45) NULL,
  `office_hour_duration` VARCHAR(45) NULL,
  `DEPARTMENT_department_number` INT NOT NULL,
  PRIMARY KEY (`professor_id`),
  INDEX `fk_PROFESSOR_DEPARTMENT_idx` (`DEPARTMENT_department_number` ASC) VISIBLE,
  CONSTRAINT `fk_PROFESSOR_DEPARTMENT`
    FOREIGN KEY (`DEPARTMENT_department_number`)
    REFERENCES `je7986_univ_db`.`DEPARTMENT` (`department_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `je7986_univ_db`.`COURSES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `je7986_univ_db`.`COURSES` (
  `course_number` INT NOT NULL,
  `course_name` VARCHAR(45) NULL,
  PRIMARY KEY (`course_number`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `je7986_univ_db`.`CLASSES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `je7986_univ_db`.`CLASSES` (
  `class_number` INT NOT NULL,
  `section_of_class` VARCHAR(45) NULL,
  `semester` VARCHAR(45) NULL,
  `year` VARCHAR(45) NULL,
  `professor` VARCHAR(45) NULL,
  `day` VARCHAR(45) NULL,
  `duration_of_class` VARCHAR(45) NULL,
  `class_hours` VARCHAR(45) NULL,
  `PROFESSOR_professor_id` INT NOT NULL,
  PRIMARY KEY (`class_number`),
  INDEX `fk_CLASSES_PROFESSOR1_idx` (`PROFESSOR_professor_id` ASC) VISIBLE,
  CONSTRAINT `fk_CLASSES_PROFESSOR1`
    FOREIGN KEY (`PROFESSOR_professor_id`)
    REFERENCES `je7986_univ_db`.`PROFESSOR` (`professor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `je7986_univ_db`.`Enrollment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `je7986_univ_db`.`Enrollment` (
  `enrollment_id` INT NOT NULL,
  `semester` VARCHAR(45) NULL,
  `section` INT NULL,
  `COURSES_course_number` INT NOT NULL,
  `STUDENT_student_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`enrollment_id`),
  INDEX `fk_Enrollment_COURSES1_idx` (`COURSES_course_number` ASC) VISIBLE,
  INDEX `fk_Enrollment_STUDENT1_idx` (`STUDENT_student_id` ASC) VISIBLE,
  CONSTRAINT `fk_Enrollment_COURSES1`
    FOREIGN KEY (`COURSES_course_number`)
    REFERENCES `je7986_univ_db`.`COURSES` (`course_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Enrollment_STUDENT1`
    FOREIGN KEY (`STUDENT_student_id`)
    REFERENCES `je7986_univ_db`.`STUDENT` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `je7986_univ_db`.`Final_Grade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `je7986_univ_db`.`Final_Grade` (
  `final_grade_id` INT NOT NULL,
  `COURSES_course_number` INT NOT NULL,
  `STUDENT_student_id` INT UNSIGNED NOT NULL,
  `Grade` VARCHAR(45) NULL,
  `semester` VARCHAR(45) NULL,
  `year` VARCHAR(45) NULL,
  `section` VARCHAR(45) NULL,
  INDEX `fk_Final_Grade_COURSES1_idx` (`COURSES_course_number` ASC) VISIBLE,
  INDEX `fk_Final_Grade_STUDENT1_idx` (`STUDENT_student_id` ASC) VISIBLE,
  PRIMARY KEY (`final_grade_id`),
  CONSTRAINT `fk_Final_Grade_COURSES1`
    FOREIGN KEY (`COURSES_course_number`)
    REFERENCES `je7986_univ_db`.`COURSES` (`course_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Final_Grade_STUDENT1`
    FOREIGN KEY (`STUDENT_student_id`)
    REFERENCES `je7986_univ_db`.`STUDENT` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
